default:
  dbconf:
    adapter: mysql2
    encoding: utf8
    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    port: 3306
    username: "{!SSM: billing/readonly/db-user}"
    password: "{!SSM: billing/readonly/db-password}"
  merritt_path: "{!ENV: MERRITT_PATH !DEFAULT: https://merritt.cdlib.org}"

# use personal credentials when configuring a local environment
# set up a script to set these variables
development:
  dbconf:
    adapter: mysql2
    encoding: utf8
    host: "{!ENV: ADMIN_HOST}"
    database: "{!ENV: ADMIN_DATABASE}"
    port: 3306
    username: "{!ENV: ADMIN_USER}"
    password: "{!ENV: ADMIN_PASSWORD}"
  merritt_path: "{!ENV: MERRITT_PATH !DEFAULT: https://merritt.cdlib.org}"
