default:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    port: 3306
    username: "{!SSM: billing/readonly/db-user}"
    password: "{!SSM: billing/readonly/db-password}"
  merritt_path: "{!SSM: ingest/config/target !DEFAULT: https://merritt.cdlib.org}"
  s3-bucket: "{!SSM: admintool/s3-bucket}"
  s3-consistency-reports: "{!SSM: admintool/s3-consistency-reports}"
  cognito-groups-allowed: "{!SSM: admintool/cognito-groups-allowed !DEFAULT: NA}"
  context: "{!SSM: admintool/context !DEFAULT: NA}"
  uc3inv_home: "{!SSM: admintool/uc3inv_home !DEFAULT: ''}"


# use personal credentials when configuring a local environment
# set up a script to set these variables
docker:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!ENV: ADMIN_HOST}"
    database: "{!ENV: ADMIN_DATABASE}"
    port: 3306
    username: "{!ENV: ADMIN_USER}"
    password: "{!ENV: ADMIN_PASSWORD}"
  merritt_path: "{!ENV: MERRITT_PATH !DEFAULT: https://merritt.cdlib.org}"
  s3-bucket: ""
  s3-consistency-reports: ""
  # Value to be checked against Cognito token - passively provided by ALB
  cognito-groups-allowed: "NONE"
  context: "NA"
  uc3inv_home: ""
