#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  lambda-container:
    image: cdluc3/uc3-mrt-admin-lambda:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SSM_ROOT_PATH: /uc3/mrt/dev/
  alb-simulate:
    volumes:
    - "./web/:/web/"