version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
    - COMMIT=`git rev-parse --short HEAD`
    - # Get semantic tags for commit otherwise get all tags for commit, sort and choose the last value
    - TAG=`(git tag --contains $COMMIT | egrep "^[0-9]+\.[0-9]+\.[0-9]+$" || git tag --contains $COMMIT || echo '') | sort | tail -1`
    - |
      if [[ "$MODE" == "OnPush" ]]
      then
        # Get Tag || Get Branch || Alternate Branch Lookup || Get Committ
        BRANCHTAG=`echo $TAG | grep . || git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || git rev-parse --short HEAD`
      else
        BRANCHTAG=$BRANCHNAME
      fi
    - DOCKTAG=$BRANCHTAG
    - COMMITDATE=`git --no-pager log -1 --pretty='format:%cd' --date='format:%Y-%m-%d %H:%M:%S'`
    - echo "Branchtag ${BRANCHTAG}; COMMITDATE=${COMMITDATE}; REPONAME=${REPONAME}; BRANCHNAME=${BRANCHNAME}"

    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  build:
    on-failure: ABORT
    commands:
    - |
      docker build --quiet --push \
        -t ${ECR_REGISTRY}/mysql-ruby-lambda mysql-ruby-lambda
    # common code is not executed as a deployed lambda... do not tag
    - |
      docker build --quiet --push \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        -t ${ECR_REGISTRY}/uc3-mrt-admin-common src-common
    # use tag or branch for the deployed image
    - |
      docker build --quiet --push \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        --build-arg COMMITDATE="${COMMITDATE}" \
        --build-arg DOCKTAG="${DOCKTAG}" \
        -t ${ECR_REGISTRY}/uc3-mrt-admin-lambda:${DOCKTAG} src-admintool
    # use tag or branch for the deployed image
    - |
      docker build --quiet --push \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        --build-arg COMMITDATE="${COMMITDATE}" \
        --build-arg DOCKTAG="${DOCKTAG}" \
        -t ${ECR_REGISTRY}/uc3-mrt-colladmin-lambda:${DOCKTAG} src-colladmin
    # the following is rarely modified by code changes
    - |
      docker build --quiet --push \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        -t ${ECR_REGISTRY}/uc3-mrt-cognitousers cognito-lambda-nonvpc

    # report results
    - mkdir -p reports
    - RPT=reports/mrt-admin-lambda.md
    - echo "## Semantic Tags" > $RPT
    - |
      git for-each-ref --sort=-creatordate --format '- %(refname) (%(creatordate:short))' refs/tags \
        | egrep "tags/[0-9]+\.[0-9]+\.[0-9]+ " \
        | sed -e "s/refs\/tags\///" | head -10 >> $RPT
    - echo "## Feature Tags" >> $RPT
    - |
      git for-each-ref --sort=-creatordate --format '- %(refname) (%(creatordate:short))' refs/tags \
        | egrep -v "tags/[0-9]+\.[0-9]+\.[0-9]+ " \
        | egrep -v "sprint-" \
        | sed -e "s/refs\/tags\///" | head -10 >> $RPT
    - |
      for img in uc3-mrt-admin-lambda uc3-mrt-colladmin-lambda
      do
        echo "## Docker Image Tags $img" >> $RPT
        aws ecr list-images --repository-name $img --filter tagStatus=TAGGED --output=text \
        | cut -f3 \
        | sed -e "s/^/- /" \
        | sort >> $RPT
      done

    - aws s3 cp $RPT s3://${S3CFBUCKET}/$RPT
    - aws cloudfront create-invalidation --distribution-id ${CFDISTRIBUTIONID} --paths /reports/* --region us-east-1