#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.9'
services:
  lambda-container:
    image: ${ECR_REGISTRY}/uc3-mrt-colladmin-lambda
    build:
      context: src-colladmin
      dockerfile: Dockerfile
      args:
        ECR_REGISTRY: ${ECR_REGISTRY}
    environment:
      SSM_ROOT_PATH: /uc3/mrt/dev/
  alb-simulate:
    volumes:
    - "./web/:/web/"