#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
networks:
  mynet:
services:
  lambda-container:
    container_name: lambda-container
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mysql-ruby-lambda
    build:
      context: mysql-ruby-lambda
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - published: 8090
      target: 8080
    networks:
      mynet:
  alb-simulate:
    container_name: alb-simulate
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/simulate-lambda-alb
    build:
      context: simulate-lambda-alb
      dockerfile: Dockerfile
    networks:
      mynet:
    environment:
      LAMBDA_DOCKER_HOST: http://lambda-container:8080
    ports:
    - published: 8091
      target: 8091
    stdin_open: true
    tty: true
    depends_on:
    - lambda-container
