#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
services:
  lambda-container:
    environment:
      MERRITT_ADMIN_CONFIG: docker
      INGEST_SERVICES: "http://${HOSTNAME}.cdlib.org:8080/ingest/"
