#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  lambda-container:
    environment:
      MERRITT_ADMIN_CONFIG: development
      USE_MYSQL: N
      USE_S3: N
      INGEST_SERVICES: "${HOSTNAME}.cdlib.org:8080/ingest/
