default:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!SSM: inv/db-host}"
    database: "{!SSM: inv/db-name}"
    port: 3306
    username: "{!SSM: inv/readwrite/db-user}"
    password: "{!SSM: inv/readwrite/db-password}"
  merritt_path: "{!ENV: MERRITT_PATH !DEFAULT: https://merritt.cdlib.org}"
  ingest-services: "{!SSM: colladmin/ingest-services}"
  ldap:
    admin_password: "{!SSM: ldap/accounts/admin/password}"
    admin_user:     "{!SSM: ldap/accounts/admin/user}"
    group_base:     "{!SSM: ldap/group_base}"
    # The lambda must go to a dedicated host rather than to a load balancer
    host:           "{!SSM: collad-ldap/host}"
    port:           "{!SSM: ldap/port}"
    user_base:      "{!SSM: ldap/user-base}"
    inst_base:      "{!SSM: ldap/inst-base}"
    ark_minter_url: "{!SSM: ldap/ark_minter_url}"
    guest_password: "{!SSM: ldap/accounts/guest/password}"
    guest_user:     "{!SSM: ldap/accounts/guest/user}"
    encryption:     "simple_tls"
    connect_timeout: 60
  s3-bucket: "{!SSM: admintool/s3-bucket}"
  s3-consistency-reports: "{!SSM: admintool/s3-consistency-reports}"
  user-pool: "{!SSM: colladmin/user-pool !DEFAULT: NA}"
  # Interface to Cognito API (via Lambda)
  cognito-users-arn: "{!SSM: cognito-users/lambda-arn-base !DEFAULT: NA}"
  cognito-groups-to-manage: "{!SSM: colladmin/cognito-groups-to-manage !DEFAULT: NA}"
  # Value to be checked against Cognito token - passively provided by ALB
  cognito-groups-allowed: "{!SSM: colladmin/cognito-groups-allowed !DEFAULT: NA}"
  context: "{!SSM: admintool/context !DEFAULT: NA}"
  # Provide state endpoints for specific subservices - not applicable for docker
  endpoints:
    ingest: 
      state: "{!SSM: ingest/port}/state?t=json"
    store: 
      state: "{!SSM: store/port}/state?t=json"
    access: 
      state: "{!SSM: store/port}/state?t=json"
    inventory: 
      state: "{!SSM: inventory/port}/mrtinv/state?t=json"
    audit: 
      state: "{!SSM: audit/port}/mrtaudit/state?t=json"
    replic: 
      state: "{!SSM: replic/port}/mrtreplic/state?t=json"
    # sword: 
    #   state: "{!SSM: sword/port}/mrtrsword/servicedocument"
    oai: 
      state: "{!SSM: oai/port}/mrtoai/state?t=json"
  replic-service: "{!SSM: colladmin/replic-service}"
  scan-use-keylist:
  - node: 9501
    keylist: 7001:scanlist/9502-210913.log 
  - node: 9502
    keylist: 7001:scanlist/9502-210913.log 

# use personal credentials when configuring a local environment
# set up a script to set these variables
docker:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: db-container
    database: db-name
    username: user
    password: password
    port: 3306
  merritt_path: "{!ENV: MERRITT_PATH !DEFAULT: https://merritt.cdlib.org}"
  ingest-services: "{!ENV: INGEST_SERVICES}"
  ldap: 
    admin_password: password
    admin_user:     cn=Directory Manager
    group_base:     ou=mrt-classes,ou=uc3,dc=cdlib,dc=org
    host:           ldap
    port:           1389
    user_base:      ou=People,ou=uc3,dc=cdlib,dc=org
    inst_base:      o=institutions,ou=uc3,dc=cdlib,dc=org
    ark_minter_url: http://noid.cdlib.org/nd/noidu_p9
    guest_password: guest
    guest_user:     anonymous
    connect_timeout: 60
  s3-bucket: ""
  s3-consistency-reports: "consistency-reports"
  user-pool: "NA"
  cognito-users-arn: "NA"
  cognito-groups-allowed: "NA"
  cognito-groups-to-manage: "NA"
  context: "NA"
  # Provide state endpoints for specific subservices - not applicable for docker
  endpoints:

