# Each yaml node is presumed to be prefixed with an SSM_ROOT_PATH for a given environment.
# 
# This file uses 3 special keywords
# - description: the descriptive text that will appear in the report
# - deprecated: create a deprecation comment indicating that a value will be changed, renamed, or removed
# - skip: skip any error checking for a node and its children when generating the report
access:
#  port:
#    description: Question - should we define an access port separately from store?
admintool:
  api-path:
    description: Path to access the Merritt Admin Tool (Query Tool)
  cognito-groups-allowed:
    description: Comma separated list of the Cognito User Groups that can access the application
  context:
    description: Client context string passed when invoking a lambda from a server (vs http)
  ecr-registry:
    description: "DEV Only: ecr registry name used to deploy the lambda"
    skip: true
    deprecated: No longer needed
  uc3-ecr-registry:
    description: "DEV Only: UC3 ecr registry name for cross-account deployment"
    skip: true
  merritt-path:
    description: "DEV Only: used to assist in computing the path to Merritt for a particular environment"
    skip: true
    deprecated: The build should not need this value
  s3-bucket:
    description: Name of the S3 bucket to store consistency reports
  s3-consistency-reports:
    description: Root path to store consistency report data within an S3 bucket
  uc3inv_home:
    description: Path to UC3 Service Inventory
  site-url:
    description: Used by mrt-cron code to create links to admin tool reports
  uc3account:
    description: Account id for the UC3 account
atom: 
  atom-credential: 
    description: |
      Authentication for atom feed retrieval.  Rotate when needed.  
      See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/misc-credential-rotate.md
      Restriction: RFC2396 compliance mandated by gem URI. (No forward slashes, ...)
box: 
  config: 
    privateAccess:
      description: |
        Box retrieval access token for ad-hoc ingest projects.  Rotate when needed. 
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/misc-credential-rotate.md
batch:
  email:
    description: Default email distribution for reports run on the Merritt batch server.
billing:
  db-host: 
    description: Hostname for the Merritt billing database server.
  db-name: 
    description: Database name for the Merritt billing database.
  readonly: &dbcred
    db-password:
      description: |
        Role specific database password.  This value should be rotated periodically.  
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/db-credential-rotate.md
    db-user:
      description: Role specific database username
  readwrite:
    <<: *dbcred
audit:
  config:  
    auditQualify:
      description: "SQL filter for audit processing - used for special circumstances"
    intervalDays:
      description: "Minimum days sleep between processing blocks - zero none"
    log: &loglev
      messageMaximumError:
        description: "Merritt Logging error message level"
      messageMaximumLevel:
        description: "Merritt Logging standard message level"
    mail:
      from:
        description: "audit report from"
        deprecated: No longer needed
      smtp:
        description: "audit report smtp service"
        deprecated: No longer needed
    nodePath:
      description: "NodeIO configuration name"
    queueCapacity:
      description: "Audit process queue: block input entry numbers from inv db"
    queueSleepMs:
      description: "Audit process queue: sleep time mS between requesting new entry block"
    sizeChecksumBuffer:
      description: "Used for maximum memory buffer size for building digests - replaces file"
    threadPool:
      description: "Number of concurrent threads for audit processing"
  port:
    description: Microservice Port
cloud:
  nodes: 
    sdsc-accessKey:
      description: |
        SDSC credential. This should be rotated periodically.
        Rotation is coordinated with SDSC staff.
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/cloud-credential-rotate.md
    sdsc-secretKey:
      description: |
        SDSC credential. This should be rotated periodically. 
        Rotation is coordinated with SDSC staff.
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/cloud-credential-rotate.md
    sdsc-s3-accessKey:
      description: |
        SDSC S3 accessKey credential. Node used for backup
    sdsc-s3-secretKey:
      description: |
        SDSC S3 secetKey credential. Nodes used for backup
    wasabi-accessKey: 
      description: |
        Wasabi credential. This should be rotated periodically. 
        Rotation is coordinated through the Wasabi admin interface.
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/cloud-credential-rotate.md
    wasabi-secretKey:
      description: |
        Wasabi credential. This should be rotated periodically. 
        Rotation is coordinated through the Wasabi admin interface.
        See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/cloud-credential-rotate.md
cognito-users:
  lambda-arn-base: 
    description: ARN to the Cognito User Management Lambda that runs outside the VPC, used by colladmin
collad-ldap:
  host: 
    description: Hostname for the ldap server accessed from the Collection Admin Tool
    deprecated: Consider renaming to colladmin/ldap/host
colladmin:
  access-service:
    description: URL to access ALB - not collection admin functions currently utilize this parameter
  api-path:
    description: Path to access the Merritt Collection Admin Tool
  cognito-groups-allowed:
    description: Comma separated list of the Cognito User Groups that can access the application
  cognito-groups-to-manage:
    description: Comma separated list of the Cognito User Groups (non SAML) that can be managed from the Collection Admin Tool
  ingest-service:
    description: URLs to the ingest load balancer
  replic-service:
    description: URL to replic instance for storage admin actions - no ALB exists
  storage-service:
    description: URL to storage ALB for storage admin actions
  inventory-service:
    description: URL to inventory ALB for inventory admin actions
  user-pool:
    description: Cognito user pool name for user management
  disable-scan-nodenums:
    description: "Disable scan buttons for a comma separated list of node numbers"
ingest:
  port:
    description: Microservice port
  ezid-user:
    description: Merritt's EZID username
  ezid-password:
    description: |
      Merritt's EZID password
      This value should be rotated periodically. 
      If you change this, please replicate this value to "/uc3/mrt/etd/default/ezid_credentials".  
      See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/ezid-credential-rotate.md
  zoo:
    lockName:
      description: Zookeeper lock name used by Ingest workers before submitting to Storage Service
  config:
    access.1:
      description: URL endpoint for Access
      deprecated: Can this be removed?
    admin:
      description: Email addresses for Ingest admins
    identifier:
      description: Description of Ingest service
    ingestQueuePath: 
      description: Path location of Ingest working area
    ingestZfsThreshold:
      description: Usage percentage used in Ingest Provisioning State
    localID:
      description: URL endpoint for Local ID service
    mail-host:
      description: SMTP server hostname
    name:
      description: Name of Ingest servie
      deprecated: Duplicate of identifier?
    numThreads:
      description: Number of worker threads in pool
    numDownloadThreads:
      description: Number of download threads in pool for retrieval
    PollingInterval:
      description: Zookeeper queue polling Interval in seconds
    QueueHoldFile:
      description: Filename that defines an Ingest pause
    store.1:
      description: URL endpoint for Storage service
    target:
      description: URL endpoint for Merritt UI
    HighPriorityThreshold:
      description: Priority threshold for processing in the high priority queue
    PollingIntervalHighPriority:
      description: Polling frequency for the high priority queue
    numThreadsHighPriority:
      description: Number of high priority threads to run
    mail-contact:
      description: Notification contact information (From:)
    mail-replyto:
      description: reply-to email (.ucop.edu) when different from send email (.cdlib.org)
inv:
  db-host: 
    description: Hostname for the Merritt inventory database server.
  db-name: 
    description: Database name for the Merritt inventory database.
  readonly: 
    <<: *dbcred
  readwrite:
    <<: *dbcred
inventory:
  port:
    description: Microservice port
  config:
    baseURI:
      description: "Example URI for inventory"
    log:
      <<: *loglev
      path: 
        description: "file path to Merritt log directory"
    zoo:
      pollMilli:
        description: "Zookeeper poll frequency"
      threadCount:
        description: "Number of concurrent threads for inventory processing"
  zoo:
    queueName:
      description: "Zookeeper name"
    queueService:
      description: "Zookeper service(s)"
    queueTimeout:
      description: "Zookeeper timeout in ms"
    lockName:
      description: "Zookeeper lock node name"
ldap:
  accounts:
    admin:
      password:
        description: |
          LDAP admin password.  This value should be rotated periodically.  
          See https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/ldap-credential-rotate.md
      user:
        description: LDAP admin username
    guest:
      password:
        description: Merritt guest password, this value is intentionally not encrypted in SSM. This value should not be rotated.
      user:
        description: Merritt guest username 
  ark_minter_url:
    description: Url to ark minting service (using "noid")
    deprecated: What does "noid" mean?
  group_base:
    description: LDAP identifier for Merritt Classes
  host:
    description: LDAP hostname alias
  inst-base:
    description: LDAP identifier for CDL
  port:
    description: Port number for the LDAP server
  user-base:
    description: LDAP identifier for Merritt Users
replic:
  config:  
    baseURI:
      description: "Appears deprecated"
    log:
      <<: *loglev
      path: 
        description: "file path to directory for replic Merritt logging"
    nodePath:
      description: "NodeIO configuration name"
    threadPool:
      description: "Number of concurrent threads for replic processing"
  scan: 
    maxkeys: 
      description: "scan: size of block for S3 keys to be processed"
    threadSleep:
      description: "scan: mS sleep between input block of S3 keys"
  port:
    description: Microservice port
store:
  config:
    baseURI:
      description: "base URI for load this storage loadbalancer - used in state commands"
    log:
      <<: *loglev
      path: 
        description: "file path to directory for store Merritt logging"
    nodePath:
      description: "NodeIO configuration name"
    numThreadsLarge:
      description: Thread pool size for Large Access workers
    numThreadsSmall:
      description: Thread pool size for Small Access workers
    verifyOnRead:
      description: "perform read digest validation on read"
    verifyOnWrite:
      description: "perform read digest validation on write"
    PollingInterval:
      description: Zookeeper queue polling Interval in seconds
    QueueHoldFile:
      description: Filename that defines Access pause
  port:
    description: Microservice port
  zoo:
    AccessLarge:
      description: Large content Access host
    AccessQSize:
      description: Byte size threshold for AccessLarge host
ui:
  master_key:
    description: Rails key for deployed ui
  global-search:
    # this could conceptually be extended to other campuses if LDAP groups existed
    ucb:
      description: |
        Comma separated list of Merritt ids with global search access in Merrit.  
        These users will need corresponding LDAP access to view results.
  upload-limit:
    description: Byte count file size limit for direct upload through the Merritt UI
  upload-limit-message:
    description: Human readable byte count file size limit for direct upload through the Merritt UI
  port:
    description: Microservice port
integ-tests: 
  skip: true
  for-stage: &inttest
    user: 
      description: merritt login (dev only); copied to UC3 SSM
    password: 
      description: merritt password (dev only); copied to UC3 SSM
  for-prod: 
    <<: *inttest      
objhealth:
  opensearch_host:
    description: Object health opensearch instance host (Prod and Dev only)
  opensearch_user:
    description: Object health opensearch user - has write access only to the objhealth index. (Prod and Dev only)
  opensearch_password:
    description: Object health opensearch password (Prod and Dev only)
  opensearch_ssl:
    description: Object health opensearch ssl (true or false). Exists in Prod and Dev only.
  merritt_credential:
    description: Readonly Merritt credential with download rights to support file identification.  Currently only implemented in Prod and Dev.
# skip error checking for dev-only special nodes
loy:
  skip: true
