# Each yaml node is presumed to be prefixed with an SSM_ROOT_PATH for a given environment.
# 
# This file uses 3 special keywords
# - description: the descriptive text that will appear in the report
# - deprecated: create a deprecation comment indicating that a value will be changed, renamed, or removed
# - skip: skip any error checking for a node and its children when generating the report
access:
#  port:
#    description: Question - should we define an access port separately from store?
admintool:
  api-path:
    description: Path to access the Merritt Admin Tool (Query Tool)
  cognito-groups-allowed:
    description: Comma separated list of the Cognito User Groups that can access the application
  context:
    description: Client context string passed when invoking a lambda from a server (vs http)
  ecr-imagem:
    description: "DEV Only: base name of the ecr image used to deploy the lambda"
    skip: true
    deprecated: No longer needed
  ecr-registry:
    description: "DEV Only: ecr registry name used to deploy the lambda"
    skip: true
    deprecated: No longer needed
  lambda-arn-base:
    description: "DEV Only: base arn name for the lambda to which code will be deployed"
    skip: true
    deprecated: No longer needed
  merritt-path:
    description: "DEV Only: used to assist in computing the path to Merritt for a particular environment"
    skip: true
    deprecated: The build should not need this value
  s3-bucket:
    description: Name of the S3 bucket to store consistency reports
  s3-consistency-reports:
    description: Root path to store consistency report data within an S3 bucket
  site-url:
    description: Path to access the Merritt Admin Tool (Query Tool)
    deprecated: Obsolete. This was used when hosting the admin tool on Cloudfront.
  uc3inv_home:
    description: Path to UC3 Service Inventory
batch:
  email:
    description: Default email distribution for reports run on the Merritt batch server.
billing:
  db-host: 
    description: Hostname for the Merritt billing database server.
  db-name: 
    description: Database name for the Merritt billing database.
  readonly: &dbcred
    db-password:
      description: Role specific database password
    db-user:
      description: Role specific database username
  readwrite:
    <<: *dbcred
audit:
  config:  
    cleanup: &cleanup
      msg:
        description: "Audit Cleanup handling email message"
      subject:
        description: "Audit Cleanup handling email subject"
      to:
        description: "Audit Cleanup handling email delivery target"
    intervalDays:
      description: "Minimum days sleep between processing blocks - zero none"
    log: &loglev
      messageMaximumError:
        description: "Merritt Logging error message level"
      messageMaximumLevel:
        description: "Merritt Logging standard message level"
    mail:
      from:
        description: "audit report from"
      smtp:
        description: "audit report smtp service"
    nodePath:
      description: "NodeIO configuration name"
    queueCapacity:
      description: "Audit process queue: block input entry numbers from inv db"
    queueSleepMs:
      description: "Audit process queue: sleep time mS between requesting new entry block"
    sizeChecksumBuffer:
      description: "Used for maximum memory buffer size for building digests - replaces file"
    threadPool:
      description: "Number of concurrent threads for audit processing"
  port:
    description: Microservice Port
cloud:
  nodes: 
    sdsc-accessKey:
      description: "SDSC credential"
    sdsc-secretKey:
      description: "SDSC credential"
    wasabi-accessKey:
      description: "Wasabi credential"
    wasabi-secretKey:
      description: "Wasabi credential"
cognito-users:
  ecr-image:
    description: "DEV Only: base name of the ecr image used to deploy the lambda"
    skip: true
    deprecated: No longer needed
  lambda-arn-base: 
    description: ARN to the Cognito User Management Lambda that runs outside the VPC, used by colladmin
collad-ldap:
  host: 
    description: Hostname for the ldap server accessed from the Collection Admin Tool
    deprecated: Consider renaming to colladmin/ldap/host
colladmin:
  api-path:
    description: Path to access the Merritt Collection Admin Tool
  cognito-groups-allowed:
    description: Comma separated list of the Cognito User Groups that can access the application
  cognito-groups-to-manage:
    description: Comma separated list of the Cognito User Groups (non SAML) that can be managed from the Collection Admin Tool
  ecr-image:
    description: "DEV Only: base name of the ecr image used to deploy the lambda"
    skip: true
    deprecated: No longer needed
  ingest-services:
    description: URLs to the running ingest instances
    deprecated: Consider performing an ec2 tag lookup instead since all instances are queried
  replic-service:
    description: URL to replic instance for storage admin actions
  storage-service:
    description: URL to storage service for storage admin actions
  inventory-service:
    description: URL to inventory service for storage admin actions
  lambda-arn-base:
    description: "DEV Only: base arn name for the lambda to which code will be deployed"
    skip: true
    deprecated: No longer needed
  user-pool:
    description: Cognito user pool name for user management
  disable-scan-nodenums:
    description: "Disable scan buttons for a comma separated list of node numbers"
ingest:
  port:
    description: Microservice port
  ezid-user:
    description: Merritt's EZID username
  ezid-password:
    description: Merritt's EZID password
  zoo:
    IngestQNames:
      description: Zookeeper queue names used by Ingest workers
    lockName:
      description: Zookeeper lock name used by Ingest workers before submitting to Storage Service
  config:
    access.1:
      description: URL endpoint for Access
      deprecated: Can this be removed?
    admin:
      description: Email addresses for Ingest admins
    identifier:
      description: Description of Ingest service
    ingestQueuePath: 
      description: Path location of Ingest working area
    localID:
      description: URL endpoint for Local ID service
    mail-host:
      description: SMTP server hostname
    name:
      description: Name of Ingest servie
      deprecated: Duplicate of identifier?
    numThreads:
      description: Number of threads in pool for request processing
    PollingInterval:
      description: Zookeeper queue polling Interval in seconds
    QueueHoldFile:
      description: Filename that defines an Ingest pause
    store.1:
      description: URL endpoint for Storage service
    target:
      description: URL endpoint for Merritt UI
inv:
  db-host: 
    description: Hostname for the Merritt inventory database server.
  db-name: 
    description: Database name for the Merritt inventory database.
  readonly: 
    <<: *dbcred
  readwrite:
    <<: *dbcred
inventory:
  port:
    description: Microservice port
  config:
    baseURI:
      description: "Example URI for inventory"
    log:
      <<: *loglev
      path: 
        description: "file path to Merritt log directory"
    zoo:
      pollMilli:
        description: "Zookeeper poll frequency"
      threadCount:
        description: "Number of concurrent threads for inventory processing"
  zoo:
    queueName:
      description: "Zookeeper name"
    queueService:
      description: "Zookeper service(s)"
    lockName:
      description: "Zookeeper lock node name"
ldap:
  accounts:
    admin:
      password:
        description: LDAP admin password
      user:
        description: LDAP admin username
    guest:
      password:
        description: Merritt guest password
      user:
        description: Merritt guest username 
  ark_minter_url:
    description: Url to ark minting service (using "noid")
    deprecated: What does "noid" mean?
  collad-host:
    description: LDAP server Hostname
    deprecated: Likely unused
  group_base:
    description: LDAP identifier for Merritt Classes
  host:
    description: LDAP hostname alias
  inst-base:
    description: LDAP identifier for CDL
  port:
    description: Port number for the LDAP server
  user-base:
    description: LDAP identifier for Merritt Users
oai:
  port:
    description: Microservice port
replic:
  config:  
    baseURI:
      description: "Appears deprecated"
    cleanup: 
      <<: *cleanup
      from:
        description: "Replic cleanup from"
    log:
      <<: *loglev
      path: 
        description: "file path to directory for replic Merritt logging"
    nodePath:
      description: "NodeIO configuration name"
    threadPool:
      description: "Number of concurrent threads for replic processing"
  scan: 
    maxkeys: 
      description: "scan: size of block for S3 keys to be processed"
    threadSleep:
      description: "scan: mS sleep between input block of S3 keys"
  port:
    description: Microservice port
store:
  config:
    baseURI:
      description: "base URI for load this storage loadbalancer - used in state commands"
    log:
      <<: *loglev
      path: 
        description: "file path to directory for store Merritt logging"
    nodePath:
      description: "NodeIO configuration name"
    numThreadsLarge:
      description: Thread pool size for Large Access workers
    numThreadsSmall:
      description: Thread pool size for Small Access workers
    verifyOnRead:
      description: "perform read digest validation on read"
    verifyOnWrite:
      description: "perform read digest validation on write"
    PollingInterval:
      description: Zookeeper queue polling Interval in seconds
    QueueHoldFile:
      description: Filename that defines Access pause
  port:
    description: Microservice port
  zoo:
    AccessLarge:
      description: Large content Access host
    AccessQSize:
      description: Byte size threshold for AccessLarge host
sword:
  port:
    description: Microservice port
ui:
  atom-credential:
    description: Credential for access Merritt atom feed
  atom-dir:
    description: Location for assembling Merritt atom feed
    deprecated: Is this used?  May be needed when eliminating the ui private repo
  dir:
    description: Runtime dir for the deployed ui instance
    deprecated: Check how this is used.  May be needed when eliminating the ui private repo
  master_key:
    description: Rails key for deployed ui
  nuxeo-base:
    description: Base url for accessing nuxeo feeds
    deprecated: Is this used?  May be needed when eliminating the ui private repo


# skip error checking for dev-only special nodes
loy:
  skip: true
