source "https://rubygems.org"

gem 'json'
gem 'mysql2'
# carefully check that the right version of this gem is installed in the mysql-ruby-lambda image
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'merritt2'
# gem 'aws-sdk-s3'  
gem 'rubyzip'
gem 'httpclient'
gem 'net-ldap'
gem 'mustache'
gem 'jwt'
