source "https://rubygems.org"

gem 'json'
gem 'mysql2'
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'main'
# gem 'aws-sdk-s3'
gem 'rubyzip'
gem 'httpclient'
gem 'net-ldap'
gem 'mustache'
