source "https://rubygems.org"

gem 'json'
gem 'mysql2'
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'main'
gem 'aws-sdk-s3'
gem 'aws-sdk-lambda'
gem 'aws-sdk-ec2'
gem 'aws-sdk-ssm'
gem 'unf_ext', '~> 0.0.7.7'
gem 'rest-client'
gem 'irb'
