source "https://rubygems.org"

gem 'json'
gem 'mysql2'
# carefully check that the right version of this gem is installed in the mysql-ruby-lambda image
# pay attention the the branch checked out during the gem build step.
# https://github.com/CDLUC3/mrt-admin-lambda/blob/main/mysql-ruby-lambda/Dockerfile#L19-L21
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'merritt2'
gem 'aws-sdk-s3'

