# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Lambda_deps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use docker to prepare dependencies
      run: |
        docker build -t depbuild .
        docker run --rm --name depbuild -d depbuild
        docker cp depbuild:/var/task/dependencies.zip .
        ls -l dependencies.zip
        echo "****** hi *****"
